### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by OkenHaha** [bartmika/django-countdowntimer-model#9]
Getting an ImportErro Saying: ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation'

When I check I found out that ugettext_lazy isn't supported in Django 4.0 anymore and instead I should use gettext_lazy instead.

Updated the issue and please look through if it can be merged.

**Comment by OkenHaha** [comment]
Please assign it to me or update the issue

**Comment by bartmika** [comment]
Thank you @OkenHaha! I've merged your change. Much appreciate you taking the time out of your day to repair and contribute.

Have a great day!

**Comment by OkenHaha** [comment]
Happy to help out!
